from .DichVu import DICHVU
from .NguoiDung import NGUOIDUNG
from .NguoiQuanLy import NGUOIQUANLY
from .KhachHang import KHACHHANG
from .NhaCungCap import NHACUNGCAP
from .ChiTietPhieuDichVu import CHITIETPHIEUDICHVU
from .PhieuDichVu import PHIEUDICHVU
from .ChiTietDonHang import CHITIETDONHANG
from .ThamSo import THAMSO
from .DonHang import DONHANG
from .SanPham import SANPHAM
from .DanhGia import DANHGIA
from .DanhMucSanPham import DANHMUC
from .BangGia import BANGGIA
from .PhieuNhap import PHIEUNHAP
from .ChiTietPhieuNhap import CHITIETPHIEUNHAP
from .TonKho import TONKHO
from .VaiTro import VAITRO
from .PhieuBanHang import PHIEUBANHANG
from .BaoCao import BAOCAO
from .Permissions import PERMISSIONS
from .NhanVien import NHANVIEN