"""Initial migration

Revision ID: 28af414c7e20
Revises: 
Create Date: 2025-07-01 19:07:49.494023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28af414c7e20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DANHMUC',
    sa.Column('MaDM', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenDM', sa.String(length=255), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MaDM')
    )
    op.create_table('DICHVU',
    sa.Column('MaDV', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenDV', sa.String(length=100), nullable=False),
    sa.Column('DonGia', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.Column('TrangThai', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('MaDV')
    )
    op.create_table('NHACUNGCAP',
    sa.Column('MaNCC', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenNCC', sa.String(length=255), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('DiaChi', sa.Text(), nullable=False),
    sa.Column('NgayHopTac', sa.Date(), nullable=True),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MaNCC'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('PERMISSIONS',
    sa.Column('PermissionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenQuyen', sa.String(length=100), nullable=False),
    sa.Column('MoTa', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID'),
    sa.UniqueConstraint('TenQuyen')
    )
    op.create_table('THAMSO',
    sa.Column('MaThamSo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenThamSo', sa.String(length=100), nullable=False),
    sa.Column('GiaTri', sa.String(length=255), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.Column('KichHoat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('MaThamSo'),
    sa.UniqueConstraint('TenThamSo')
    )
    op.create_table('VAITRO',
    sa.Column('MaVaiTro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenVaiTro', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('MaVaiTro'),
    sa.UniqueConstraint('TenVaiTro')
    )
    op.create_table('NGUOIDUNG',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenDangNhap', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('MatKhau', sa.String(length=255), nullable=False),
    sa.Column('MaVaiTro', sa.Integer(), nullable=False),
    sa.Column('TaoNgay', sa.DateTime(), nullable=True),
    sa.Column('HoTen', sa.String(length=100), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=False),
    sa.Column('DiaChi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['MaVaiTro'], ['VAITRO.MaVaiTro'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('TenDangNhap')
    )
    op.create_table('ROLE_PERMISSIONS',
    sa.Column('MaVaiTro', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MaVaiTro'], ['VAITRO.MaVaiTro'], ),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSIONS.PermissionID'], ),
    sa.PrimaryKeyConstraint('MaVaiTro', 'PermissionID')
    )
    op.create_table('SANPHAM',
    sa.Column('MaSP', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenSP', sa.String(length=255), nullable=False),
    sa.Column('MaDM', sa.Integer(), nullable=False),
    sa.Column('MaNCC', sa.Integer(), nullable=False),
    sa.Column('GiaBan', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('SoLuongTon', sa.Integer(), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.Column('HinhAnh', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['MaDM'], ['DANHMUC.MaDM'], ),
    sa.ForeignKeyConstraint(['MaNCC'], ['NHACUNGCAP.MaNCC'], ),
    sa.PrimaryKeyConstraint('MaSP')
    )
    op.create_table('BANGGIA',
    sa.Column('MaBG', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('GiaBan', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('GiaNhap', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('NgayCapNhat', sa.DateTime(), nullable=True),
    sa.Column('NguonCapNhat', sa.Enum('Thủ công', 'API'), nullable=True),
    sa.CheckConstraint('GiaBan >= 0', name='check_giaban_non_negative'),
    sa.CheckConstraint('GiaNhap >= 0', name='check_gianhap_non_negative'),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaBG')
    )
    op.create_table('BAOCAO',
    sa.Column('MaBC', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LoaiBaoCao', sa.Enum('Doanh thu', 'Tồn kho', 'Lợi nhuận'), nullable=False),
    sa.Column('ThoiGianBaoCao', sa.Date(), nullable=False),
    sa.Column('DuLieu', sa.JSON(), nullable=False),
    sa.Column('TaoNgay', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('NguoiTao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NguoiTao'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaBC')
    )
    op.create_table('KHACHHANG',
    sa.Column('MaKH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('HoTen', sa.String(length=100), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=False),
    sa.Column('DiaChi', sa.Text(), nullable=False),
    sa.Column('NgayDangKy', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MaKH')
    )
    op.create_table('NGUOIQUANLY',
    sa.Column('MaQL', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('HoTen', sa.String(length=100), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=False),
    sa.Column('DiaChi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MaQL')
    )
    op.create_table('NHANVIEN',
    sa.Column('MaNV', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('TenNV', sa.String(length=100), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=False),
    sa.Column('DiaChi', sa.Text(), nullable=True),
    sa.Column('NgayVaoLam', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaNV')
    )
    op.create_table('PHIEUNHAP',
    sa.Column('MaPN', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaNCC', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('NgayNhap', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('TongTien', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('TrangThai', sa.Enum('da_nhap', 'dang_xu_ly', 'huy', name='trangthaiphieunhapenum'), nullable=False),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['MaNCC'], ['NHACUNGCAP.MaNCC'], ),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaPN')
    )
    op.create_table('TONKHO',
    sa.Column('MaTK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('SoLuongTon', sa.Integer(), nullable=False),
    sa.Column('NgayCapNhat', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('MucCanhBao', sa.Integer(), nullable=False),
    sa.CheckConstraint('SoLuongTon >= 0', name='check_soluongton_nonnegative'),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaTK')
    )
    op.create_table('USER_PERMISSIONS',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('PermissionID', sa.Integer(), nullable=False),
    sa.Column('IsGranted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['PERMISSIONS.PermissionID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('UserID', 'PermissionID')
    )
    op.create_table('CHITIETPHIEUNHAP',
    sa.Column('MaCTPN', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaPN', sa.Integer(), nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('SoLuong', sa.Integer(), nullable=False),
    sa.Column('DonGiaNhap', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('ThanhTien', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('SoLuong > 0', name='check_soluong_positive'),
    sa.ForeignKeyConstraint(['MaPN'], ['PHIEUNHAP.MaPN'], ),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaCTPN')
    )
    op.create_table('DANHGIA',
    sa.Column('MaDG', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=True),
    sa.Column('MaKH', sa.Integer(), nullable=True),
    sa.Column('XepHang', sa.Integer(), nullable=False),
    sa.Column('TieuDe', sa.String(length=255), nullable=False),
    sa.Column('NoiDung', sa.Text(), nullable=False),
    sa.Column('NgayDANHGIA', sa.DateTime(), nullable=True),
    sa.Column('HinhAnh', sa.String(length=255), nullable=True),
    sa.CheckConstraint('XepHang BETWEEN 1 AND 5', name='check_xephang_range'),
    sa.ForeignKeyConstraint(['MaKH'], ['KHACHHANG.MaKH'], ),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaDG')
    )
    op.create_table('DONHANG',
    sa.Column('MaDH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaKH', sa.Integer(), nullable=False),
    sa.Column('NgayDat', sa.DateTime(), nullable=False),
    sa.Column('TongTien', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TrangThai', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['MaKH'], ['KHACHHANG.MaKH'], ),
    sa.PrimaryKeyConstraint('MaDH')
    )
    op.create_table('PHIEUDICHVU',
    sa.Column('MaPDV', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaKH', sa.Integer(), nullable=False),
    sa.Column('NgayLap', sa.DateTime(), nullable=False),
    sa.Column('TongTien', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TraTruoc', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.Column('TrangThai', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['MaKH'], ['KHACHHANG.MaKH'], ),
    sa.PrimaryKeyConstraint('MaPDV')
    )
    op.create_table('CHITIETDONHANG',
    sa.Column('MaCTDH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaDH', sa.Integer(), nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('SoLuong', sa.Integer(), nullable=False),
    sa.Column('GiaBan', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('ThanhTien', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['MaDH'], ['DONHANG.MaDH'], ),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaCTDH')
    )
    op.create_table('CHITIETPHIEUDICHVU',
    sa.Column('MaCT', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaPDV', sa.Integer(), nullable=False),
    sa.Column('MaDV', sa.Integer(), nullable=False),
    sa.Column('DonGiaDichVu', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('DonGiaDuocTinh', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('SoLuong', sa.Integer(), nullable=True),
    sa.Column('ThanhTien', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('TienTraTruoc', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('TienConLai', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('NgayGiao', sa.Date(), nullable=True),
    sa.Column('TinhTrang', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['MaDV'], ['DICHVU.MaDV'], ),
    sa.ForeignKeyConstraint(['MaPDV'], ['PHIEUDICHVU.MaPDV'], ),
    sa.PrimaryKeyConstraint('MaCT')
    )
    op.create_table('PHIEUBANHANG',
    sa.Column('MaPhieuBan', sa.String(length=20), nullable=False),
    sa.Column('MaDH', sa.Integer(), nullable=False),
    sa.Column('NgayLap', sa.Date(), nullable=False),
    sa.Column('TongTien', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('PhuongThucThanhToan', sa.String(length=50), nullable=False),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['MaDH'], ['DONHANG.MaDH'], ),
    sa.PrimaryKeyConstraint('MaPhieuBan')
    )
    op.drop_table('user_permissions')
    op.drop_table('donhang')
    op.drop_table('dichvu')
    op.drop_table('baocao')
    op.drop_table('chitietphieudichvu')
    op.drop_table('nguoiquanly')
    op.drop_table('phieubanhang')
    op.drop_table('phieudichvu')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('TenQuyen'))

    op.drop_table('permissions')
    with op.batch_alter_table('nguoidung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Email'))
        batch_op.drop_index(batch_op.f('TenDangNhap'))

    op.drop_table('nguoidung')
    op.drop_table('danhmuc')
    op.drop_table('chitietdonhang')
    op.drop_table('role_permissions')
    op.drop_table('banggia')
    op.drop_table('tonkho')
    op.drop_table('phieunhap')
    with op.batch_alter_table('vaitro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('TenVaiTro'))

    op.drop_table('vaitro')
    op.drop_table('nhanvien')
    op.drop_table('chitietphieunhap')
    op.drop_table('danhgia')
    op.drop_table('khachhang')
    with op.batch_alter_table('nhacungcap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('Email'))

    op.drop_table('nhacungcap')
    op.drop_table('sanpham')
    with op.batch_alter_table('thamso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('TenThamSo'))

    op.drop_table('thamso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thamso',
    sa.Column('MaThamSo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenThamSo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('GiaTri', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MoTa', mysql.TEXT(), nullable=True),
    sa.Column('KichHoat', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MaThamSo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('thamso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('TenThamSo'), ['TenThamSo'], unique=True)

    op.create_table('sanpham',
    sa.Column('MaSP', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenSP', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MaDM', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MaNCC', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('GiaBan', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('SoLuongTon', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MoTa', mysql.TEXT(), nullable=True),
    sa.Column('HinhAnh', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['MaDM'], ['danhmuc.MaDM'], name='sanpham_ibfk_1'),
    sa.ForeignKeyConstraint(['MaNCC'], ['nhacungcap.MaNCC'], name='sanpham_ibfk_2'),
    sa.PrimaryKeyConstraint('MaSP'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nhacungcap',
    sa.Column('MaNCC', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenNCC', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('SoDienThoai', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('DiaChi', mysql.TEXT(), nullable=False),
    sa.Column('NgayHopTac', sa.DATE(), nullable=True),
    sa.Column('GhiChu', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('MaNCC'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nhacungcap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('Email'), ['Email'], unique=True)

    op.create_table('khachhang',
    sa.Column('MaKH', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('HoTen', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('SoDienThoai', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('DiaChi', mysql.TEXT(), nullable=False),
    sa.Column('NgayDangKy', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['nguoidung.UserID'], name='khachhang_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MaKH'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('danhgia',
    sa.Column('MaDG', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaSP', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('MaKH', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('XepHang', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TieuDe', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('NoiDung', mysql.TEXT(), nullable=False),
    sa.Column('NgayDANHGIA', mysql.DATETIME(), nullable=True),
    sa.Column('HinhAnh', mysql.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('(`XepHang` between 1 and 5)', name=op.f('check_xephang_range')),
    sa.ForeignKeyConstraint(['MaKH'], ['khachhang.MaKH'], name=op.f('danhgia_ibfk_2')),
    sa.ForeignKeyConstraint(['MaSP'], ['sanpham.MaSP'], name=op.f('danhgia_ibfk_1')),
    sa.PrimaryKeyConstraint('MaDG'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chitietphieunhap',
    sa.Column('MaCTPN', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaPN', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MaSP', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SoLuong', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DonGiaNhap', mysql.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('ThanhTien', mysql.DECIMAL(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('(`SoLuong` > 0)', name=op.f('check_soluong_positive')),
    sa.ForeignKeyConstraint(['MaPN'], ['phieunhap.MaPN'], name=op.f('chitietphieunhap_ibfk_1')),
    sa.ForeignKeyConstraint(['MaSP'], ['sanpham.MaSP'], name=op.f('chitietphieunhap_ibfk_2')),
    sa.PrimaryKeyConstraint('MaCTPN'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nhanvien',
    sa.Column('MaNV', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TenNV', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('SoDienThoai', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('DiaChi', mysql.TEXT(), nullable=True),
    sa.Column('NgayVaoLam', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['nguoidung.UserID'], name=op.f('nhanvien_ibfk_1')),
    sa.PrimaryKeyConstraint('MaNV'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vaitro',
    sa.Column('MaVaiTro', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenVaiTro', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('MaVaiTro'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vaitro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('TenVaiTro'), ['TenVaiTro'], unique=True)

    op.create_table('phieunhap',
    sa.Column('MaPN', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaNCC', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NgayNhap', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('TongTien', mysql.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('TrangThai', mysql.ENUM('da_nhap', 'dang_xu_ly', 'huy'), nullable=False),
    sa.Column('GhiChu', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['MaNCC'], ['nhacungcap.MaNCC'], name=op.f('phieunhap_ibfk_1')),
    sa.ForeignKeyConstraint(['UserID'], ['nguoidung.UserID'], name=op.f('phieunhap_ibfk_2')),
    sa.PrimaryKeyConstraint('MaPN'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tonkho',
    sa.Column('MaTK', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaSP', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SoLuongTon', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NgayCapNhat', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('MucCanhBao', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`SoLuongTon` >= 0)', name=op.f('check_soluongton_nonnegative')),
    sa.ForeignKeyConstraint(['MaSP'], ['sanpham.MaSP'], name=op.f('tonkho_ibfk_1')),
    sa.PrimaryKeyConstraint('MaTK'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('banggia',
    sa.Column('MaBG', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaSP', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('GiaBan', mysql.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('GiaNhap', mysql.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('NgayCapNhat', mysql.DATETIME(), nullable=True),
    sa.Column('NguonCapNhat', mysql.ENUM('Thủ công', 'API'), nullable=True),
    sa.CheckConstraint('(`GiaBan` >= 0)', name=op.f('check_giaban_non_negative')),
    sa.CheckConstraint('(`GiaNhap` >= 0)', name=op.f('check_gianhap_non_negative')),
    sa.ForeignKeyConstraint(['MaSP'], ['sanpham.MaSP'], name=op.f('banggia_ibfk_1')),
    sa.PrimaryKeyConstraint('MaBG'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('MaVaiTro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PermissionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['MaVaiTro'], ['vaitro.MaVaiTro'], name=op.f('role_permissions_ibfk_1')),
    sa.ForeignKeyConstraint(['PermissionID'], ['permissions.PermissionID'], name=op.f('role_permissions_ibfk_2')),
    sa.PrimaryKeyConstraint('MaVaiTro', 'PermissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chitietdonhang',
    sa.Column('MaCTDH', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaDH', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MaSP', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SoLuong', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('GiaBan', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('ThanhTien', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['MaDH'], ['donhang.MaDH'], name=op.f('chitietdonhang_ibfk_1')),
    sa.ForeignKeyConstraint(['MaSP'], ['sanpham.MaSP'], name=op.f('chitietdonhang_ibfk_2')),
    sa.PrimaryKeyConstraint('MaCTDH'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('danhmuc',
    sa.Column('MaDM', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenDM', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MoTa', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('MaDM'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nguoidung',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenDangNhap', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('MatKhau', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('MaVaiTro', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('TaoNgay', mysql.DATETIME(), nullable=True),
    sa.Column('HoTen', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('SoDienThoai', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('DiaChi', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['MaVaiTro'], ['vaitro.MaVaiTro'], name='nguoidung_ibfk_1'),
    sa.PrimaryKeyConstraint('UserID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('nguoidung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('TenDangNhap'), ['TenDangNhap'], unique=True)
        batch_op.create_index(batch_op.f('Email'), ['Email'], unique=True)

    op.create_table('permissions',
    sa.Column('PermissionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenQuyen', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('MoTa', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('PermissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('TenQuyen'), ['TenQuyen'], unique=True)

    op.create_table('phieudichvu',
    sa.Column('MaPDV', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaKH', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NgayLap', mysql.DATETIME(), nullable=False),
    sa.Column('TongTien', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TraTruoc', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GhiChu', mysql.TEXT(), nullable=True),
    sa.Column('TrangThai', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['MaKH'], ['khachhang.MaKH'], name='phieudichvu_ibfk_1'),
    sa.PrimaryKeyConstraint('MaPDV'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('phieubanhang',
    sa.Column('MaPhieuBan', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('MaDH', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NgayLap', sa.DATE(), nullable=False),
    sa.Column('TongTien', mysql.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('PhuongThucThanhToan', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('GhiChu', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['MaDH'], ['donhang.MaDH'], name=op.f('phieubanhang_ibfk_1')),
    sa.PrimaryKeyConstraint('MaPhieuBan'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('nguoiquanly',
    sa.Column('MaQL', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('HoTen', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('SoDienThoai', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('DiaChi', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['nguoidung.UserID'], name=op.f('nguoiquanly_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MaQL'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('chitietphieudichvu',
    sa.Column('MaCT', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaPDV', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('MaDV', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DonGiaDichVu', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('DonGiaDuocTinh', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('SoLuong', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ThanhTien', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('TienTraTruoc', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('TienConLai', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('NgayGiao', sa.DATE(), nullable=True),
    sa.Column('TinhTrang', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['MaDV'], ['dichvu.MaDV'], name=op.f('chitietphieudichvu_ibfk_2')),
    sa.ForeignKeyConstraint(['MaPDV'], ['phieudichvu.MaPDV'], name=op.f('chitietphieudichvu_ibfk_1')),
    sa.PrimaryKeyConstraint('MaCT'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('baocao',
    sa.Column('MaBC', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('LoaiBaoCao', mysql.ENUM('Doanh thu', 'Tồn kho', 'Lợi nhuận'), nullable=False),
    sa.Column('ThoiGianBaoCao', sa.DATE(), nullable=False),
    sa.Column('DuLieu', mysql.JSON(), nullable=False),
    sa.Column('TaoNgay', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('NguoiTao', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['NguoiTao'], ['nguoidung.UserID'], name=op.f('baocao_ibfk_1')),
    sa.PrimaryKeyConstraint('MaBC'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dichvu',
    sa.Column('MaDV', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('TenDV', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('DonGia', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('MoTa', mysql.TEXT(), nullable=True),
    sa.Column('TrangThai', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MaDV'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('donhang',
    sa.Column('MaDH', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MaKH', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NgayDat', mysql.DATETIME(), nullable=False),
    sa.Column('TongTien', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TrangThai', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['MaKH'], ['khachhang.MaKH'], name=op.f('donhang_ibfk_1')),
    sa.PrimaryKeyConstraint('MaDH'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_permissions',
    sa.Column('UserID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('PermissionID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('IsGranted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['PermissionID'], ['permissions.PermissionID'], name=op.f('user_permissions_ibfk_2')),
    sa.ForeignKeyConstraint(['UserID'], ['nguoidung.UserID'], name=op.f('user_permissions_ibfk_1')),
    sa.PrimaryKeyConstraint('UserID', 'PermissionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('PHIEUBANHANG')
    op.drop_table('CHITIETPHIEUDICHVU')
    op.drop_table('CHITIETDONHANG')
    op.drop_table('PHIEUDICHVU')
    op.drop_table('DONHANG')
    op.drop_table('DANHGIA')
    op.drop_table('CHITIETPHIEUNHAP')
    op.drop_table('USER_PERMISSIONS')
    op.drop_table('TONKHO')
    op.drop_table('PHIEUNHAP')
    op.drop_table('NHANVIEN')
    op.drop_table('NGUOIQUANLY')
    op.drop_table('KHACHHANG')
    op.drop_table('BAOCAO')
    op.drop_table('BANGGIA')
    op.drop_table('SANPHAM')
    op.drop_table('ROLE_PERMISSIONS')
    op.drop_table('NGUOIDUNG')
    op.drop_table('VAITRO')
    op.drop_table('THAMSO')
    op.drop_table('PERMISSIONS')
    op.drop_table('NHACUNGCAP')
    op.drop_table('DICHVU')
    op.drop_table('DANHMUC')
    # ### end Alembic commands ###
