"""Initial migration

Revision ID: a5165d48524b
Revises: 
Create Date: 2025-06-14 15:59:05.719517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5165d48524b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DANHMUC',
    sa.Column('MaDM', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenDM', sa.String(length=255), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MaDM')
    )
    op.create_table('DICHVU',
    sa.Column('MaDV', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenDV', sa.String(length=100), nullable=False),
    sa.Column('DonGia', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.Column('TrangThai', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('MaDV')
    )
    op.create_table('NGUOIDUNG',
    sa.Column('UserID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenDangNhap', sa.String(length=100), nullable=False),
    sa.Column('Email', sa.String(length=100), nullable=False),
    sa.Column('MatKhau', sa.String(length=255), nullable=False),
    sa.Column('VaiTro', sa.Enum('admin', 'customer'), nullable=False),
    sa.Column('TaoNgay', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email'),
    sa.UniqueConstraint('TenDangNhap')
    )
    op.create_table('NHACUNGCAP',
    sa.Column('MaNCC', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenNCC', sa.String(length=255), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=100), nullable=True),
    sa.Column('DiaChi', sa.Text(), nullable=False),
    sa.Column('NgayHopTac', sa.Date(), nullable=True),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('MaNCC'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('THAMSO',
    sa.Column('MaThamSo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenThamSo', sa.String(length=100), nullable=False),
    sa.Column('GiaTri', sa.String(length=255), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.Column('KichHoat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('MaThamSo'),
    sa.UniqueConstraint('TenThamSo')
    )
    op.create_table('VAITRO',
    sa.Column('MaVaiTro', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenVaiTro', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('MaVaiTro'),
    sa.UniqueConstraint('TenVaiTro')
    )
    op.create_table('BAOCAO',
    sa.Column('MaBC', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('LoaiBaoCao', sa.Enum('Doanh thu', 'Tồn kho', 'Lợi nhuận'), nullable=False),
    sa.Column('ThoiGianBaoCao', sa.Date(), nullable=False),
    sa.Column('DuLieu', sa.JSON(), nullable=False),
    sa.Column('TaoNgay', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('NguoiTao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['NguoiTao'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaBC')
    )
    op.create_table('KHACHHANG',
    sa.Column('MaKH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('HoTen', sa.String(length=100), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=False),
    sa.Column('DiaChi', sa.Text(), nullable=False),
    sa.Column('NgayDangKy', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaKH')
    )
    op.create_table('NGUOIQUANLY',
    sa.Column('MaQL', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('HoTen', sa.String(length=100), nullable=False),
    sa.Column('SoDienThoai', sa.String(length=15), nullable=False),
    sa.Column('DiaChi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaQL')
    )
    op.create_table('PHIEUNHAP',
    sa.Column('MaPN', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaNCC', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('NgayNhap', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('TongTien', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('TrangThai', sa.Enum('da_nhap', 'dang_xu_ly', 'huy', name='trangthaiphieunhapenum'), nullable=False),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['MaNCC'], ['NHACUNGCAP.MaNCC'], ),
    sa.ForeignKeyConstraint(['UserID'], ['NGUOIDUNG.UserID'], ),
    sa.PrimaryKeyConstraint('MaPN')
    )
    op.create_table('SANPHAM',
    sa.Column('MaSP', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TenSP', sa.String(length=255), nullable=False),
    sa.Column('MaDM', sa.Integer(), nullable=False),
    sa.Column('MaNCC', sa.Integer(), nullable=False),
    sa.Column('GiaBan', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('SoLuongTon', sa.Integer(), nullable=False),
    sa.Column('MoTa', sa.Text(), nullable=True),
    sa.Column('HinhAnh', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['MaDM'], ['DANHMUC.MaDM'], ),
    sa.ForeignKeyConstraint(['MaNCC'], ['NHACUNGCAP.MaNCC'], ),
    sa.PrimaryKeyConstraint('MaSP')
    )
    op.create_table('BANGGIA',
    sa.Column('MaBG', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('GiaBan', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('GiaNhap', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('NgayCapNhat', sa.DateTime(), nullable=True),
    sa.Column('NguonCapNhat', sa.Enum('Thủ công', 'API'), nullable=True),
    sa.CheckConstraint('GiaBan >= 0', name='check_giaban_non_negative'),
    sa.CheckConstraint('GiaNhap >= 0', name='check_gianhap_non_negative'),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaBG')
    )
    op.create_table('CHITIETPHIEUNHAP',
    sa.Column('MaCTPN', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaPN', sa.Integer(), nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('SoLuong', sa.Integer(), nullable=False),
    sa.Column('DonGiaNhap', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.Column('ThanhTien', sa.DECIMAL(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('SoLuong > 0', name='check_soluong_positive'),
    sa.ForeignKeyConstraint(['MaPN'], ['PHIEUNHAP.MaPN'], ),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaCTPN')
    )
    op.create_table('DANHGIA',
    sa.Column('MaDG', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=True),
    sa.Column('MaKH', sa.Integer(), nullable=True),
    sa.Column('XepHang', sa.Integer(), nullable=False),
    sa.Column('TieuDe', sa.String(length=255), nullable=False),
    sa.Column('NoiDung', sa.Text(), nullable=False),
    sa.Column('NgayDANHGIA', sa.DateTime(), nullable=True),
    sa.Column('HinhAnh', sa.String(length=255), nullable=True),
    sa.CheckConstraint('XepHang BETWEEN 1 AND 5', name='check_xephang_range'),
    sa.ForeignKeyConstraint(['MaKH'], ['KHACHHANG.MaKH'], ),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaDG')
    )
    op.create_table('DONHANG',
    sa.Column('MaDH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaKH', sa.Integer(), nullable=False),
    sa.Column('NgayDat', sa.DateTime(), nullable=False),
    sa.Column('TongTien', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TrangThai', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['MaKH'], ['KHACHHANG.MaKH'], ),
    sa.PrimaryKeyConstraint('MaDH')
    )
    op.create_table('PHIEUDICHVU',
    sa.Column('MaPDV', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaKH', sa.Integer(), nullable=False),
    sa.Column('NgayLap', sa.DateTime(), nullable=False),
    sa.Column('TongTien', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('TraTruoc', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.Column('TrangThai', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['MaKH'], ['KHACHHANG.MaKH'], ),
    sa.PrimaryKeyConstraint('MaPDV')
    )
    op.create_table('TONKHO',
    sa.Column('MaTK', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('SoLuongTon', sa.Integer(), nullable=False),
    sa.Column('NgayCapNhat', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('MucCanhBao', sa.Integer(), nullable=False),
    sa.CheckConstraint('SoLuongTon >= 0', name='check_soluongton_nonnegative'),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaTK')
    )
    op.create_table('CHITIETDONHANG',
    sa.Column('MaCTDH', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaDH', sa.Integer(), nullable=False),
    sa.Column('MaSP', sa.Integer(), nullable=False),
    sa.Column('SoLuong', sa.Integer(), nullable=False),
    sa.Column('GiaBan', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('ThanhTien', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['MaDH'], ['DONHANG.MaDH'], ),
    sa.ForeignKeyConstraint(['MaSP'], ['SANPHAM.MaSP'], ),
    sa.PrimaryKeyConstraint('MaCTDH')
    )
    op.create_table('CHITIETPHIEUDICHVU',
    sa.Column('MaCT', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('MaPDV', sa.Integer(), nullable=False),
    sa.Column('MaDV', sa.Integer(), nullable=False),
    sa.Column('DonGiaDichVu', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('DonGiaDuocTinh', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('SoLuong', sa.Integer(), nullable=True),
    sa.Column('ThanhTien', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('TienTraTruoc', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('TienConLai', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('NgayGiao', sa.Date(), nullable=True),
    sa.Column('TinhTrang', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['MaDV'], ['DICHVU.MaDV'], ),
    sa.ForeignKeyConstraint(['MaPDV'], ['PHIEUDICHVU.MaPDV'], ),
    sa.PrimaryKeyConstraint('MaCT')
    )
    op.create_table('PHIEUBANHANG',
    sa.Column('MaPhieuBan', sa.String(length=20), nullable=False),
    sa.Column('MaDH', sa.Integer(), nullable=False),
    sa.Column('NgayLap', sa.Date(), nullable=False),
    sa.Column('TongTien', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('PhuongThucThanhToan', sa.String(length=50), nullable=False),
    sa.Column('GhiChu', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['MaDH'], ['DONHANG.MaDH'], ),
    sa.PrimaryKeyConstraint('MaPhieuBan')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PHIEUBANHANG')
    op.drop_table('CHITIETPHIEUDICHVU')
    op.drop_table('CHITIETDONHANG')
    op.drop_table('TONKHO')
    op.drop_table('PHIEUDICHVU')
    op.drop_table('DONHANG')
    op.drop_table('DANHGIA')
    op.drop_table('CHITIETPHIEUNHAP')
    op.drop_table('BANGGIA')
    op.drop_table('SANPHAM')
    op.drop_table('PHIEUNHAP')
    op.drop_table('NGUOIQUANLY')
    op.drop_table('KHACHHANG')
    op.drop_table('BAOCAO')
    op.drop_table('VAITRO')
    op.drop_table('THAMSO')
    op.drop_table('NHACUNGCAP')
    op.drop_table('NGUOIDUNG')
    op.drop_table('DICHVU')
    op.drop_table('DANHMUC')
    # ### end Alembic commands ###
